server:
  error:
    include-message: always
library:
  books-rest-client:
    host: localhost
    port: 8082
  rest-clients:
    - name: users
      host: localhost
      port: 8081
    - name: rentals
      host: localhost
      port: 8083
